[features]
seeds = false
skip-lint = false
[programs.localnet]
chainquest = "FTntTxns1WBfqQZp9ng1b2knmg24r5jXz2wAtPPAzFK7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/lumiadeployer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
